# Generated by Django 5.1.4 on 2024-12-11 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ref', 'Sędzia'), ('kol', 'Kolegium')], default='undefined', max_length=20),
        ),
    ]
